/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-spring-conversation:src/main/java/converter/JsfConverter.e.vm.java
 */
package org.ikane.demospringfuse.web.converter.more;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;
import org.ikane.demospringfuse.domain.more.MoreTypesDemo;
import org.ikane.demospringfuse.repository.more.MoreTypesDemoRepository;
import org.ikane.demospringfuse.web.converter.GenericJsfConverter;

/**
 * JSF Converter for {@link MoreTypesDemo}.
 */
@Named
@Singleton
public class MoreTypesDemoJsfConverter extends GenericJsfConverter<MoreTypesDemo, Integer> {
    @Inject
    public MoreTypesDemoJsfConverter(MoreTypesDemoRepository moreTypesDemoRepository) {
        super(moreTypesDemoRepository, MoreTypesDemo.class, Integer.class);
    }
}