/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-spring-conversation:src/main/java/domain/UploadHandler.e.vm.java
 */
package org.ikane.demospringfuse.web.domain;

import static org.apache.commons.codec.binary.StringUtils.newStringUtf8;
import org.apache.commons.io.FilenameUtils;
import org.ikane.demospringfuse.domain.Document;
import org.primefaces.event.FileUploadEvent;
import org.primefaces.model.UploadedFile;

public class DocumentUploadHandler {
    private Document document;

    public DocumentUploadHandler(Document document) {
        this.document = document;
    }

    /**
     * Primefaces support for documentBinary file upload
     */
    public void handleFileUpload(FileUploadEvent fileUploadEvent) {
        UploadedFile uploadedFile = fileUploadEvent.getFile(); //application code
        document.setDocumentBinary(uploadedFile.getContents());
        document.setDocumentSize(document.getDocumentBinary().length);
        document.setDocumentContentType(uploadedFile.getContentType());
        String filename = FilenameUtils.getName(uploadedFile.getFileName());
        document.setDocumentFileName(newStringUtf8(filename.getBytes())); //until primefaces bug #3002 is resolved
    }
}