/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-spring-conversation:src/main/java/domain/LazyDataModel.e.vm.java
 */
package org.ikane.demospringfuse.web.domain;

import static org.ikane.demospringfuse.web.conversation.ConversationHolder.getCurrentConversation;
import java.util.Arrays;
import javax.faces.convert.Converter;
import javax.inject.Inject;
import javax.inject.Named;
import org.ikane.demospringfuse.domain.Document;
import org.ikane.demospringfuse.repository.DocumentRepository;
import org.ikane.demospringfuse.repository.support.Repository;
import org.ikane.demospringfuse.web.conversation.ConversationContext;
import org.ikane.demospringfuse.web.converter.DocumentJsfConverter;
import org.ikane.demospringfuse.web.domain.support.GenericLazyDataModel;
import org.ikane.demospringfuse.web.domain.support.GenericSearchForm;
import org.springframework.context.annotation.Scope;

/**
 * Provides server-side pagination for search.
 * TODO: dependencies wiring after deserialization (get inspiration from http://jira.springframework.org/browse/SWF-1224 )
 */
@Named
@Scope("conversation")
public class DocumentLazyDataModel extends GenericLazyDataModel<Document, String, DocumentSearchForm> {
    private static final long serialVersionUID = 1L;

    @Inject
    transient private DocumentRepository documentRepository;
    @Inject
    transient private DocumentJsfConverter documentConverter;
    @Inject
    transient private DocumentSearchForm documentSearchForm;

    private Document[] selectedRows;

    @Override
    protected Repository<Document, String> getRepository() {
        return documentRepository;
    }

    @Override
    protected Converter getConverter() {
        return documentConverter;
    }

    @Override
    protected GenericSearchForm<Document, DocumentSearchForm> getSearchForm() {
        return documentSearchForm;
    }

    @Override
    protected ConversationContext<Document> getSelectedContext(Document selected) {
        if (selected.isIdSet()) {
            // just the id matters as we want to reload it in the conversation entity manager.
            return DocumentController.newEditContext(selected.getId());
        } else {
            return DocumentController.newEditContext(selected); // fresh entity (creation)
        }
    }

    // -----------------------------------
    // Multi selection support
    // -----------------------------------

    public void setSelectedRows(Document[] selectedRows) {
        this.selectedRows = selectedRows;
    }

    public Document[] getSelectedRows() {
        return selectedRows;
    }

    public String multiSelect() {
        return getCurrentConversation() //
                .<ConversationContext<Document>> getCurrentContext() //
                .getCallBack() //
                .selected(Arrays.asList(selectedRows));
    }
}