/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-spring-conversation:src/main/java/domain/LazyDataModel.e.vm.java
 */
package org.ikane.demospringfuse.web.domain;

import static org.ikane.demospringfuse.web.conversation.ConversationHolder.getCurrentConversation;
import java.util.Arrays;
import javax.faces.convert.Converter;
import javax.inject.Inject;
import javax.inject.Named;
import org.ikane.demospringfuse.domain.Legacy;
import org.ikane.demospringfuse.domain.LegacyPk;
import org.ikane.demospringfuse.repository.LegacyRepository;
import org.ikane.demospringfuse.repository.support.Repository;
import org.ikane.demospringfuse.web.conversation.ConversationContext;
import org.ikane.demospringfuse.web.converter.LegacyJsfConverter;
import org.ikane.demospringfuse.web.domain.support.GenericLazyDataModel;
import org.ikane.demospringfuse.web.domain.support.GenericSearchForm;
import org.springframework.context.annotation.Scope;

/**
 * Provides server-side pagination for search.
 * TODO: dependencies wiring after deserialization (get inspiration from http://jira.springframework.org/browse/SWF-1224 )
 */
@Named
@Scope("conversation")
public class LegacyLazyDataModel extends GenericLazyDataModel<Legacy, LegacyPk, LegacySearchForm> {
    private static final long serialVersionUID = 1L;

    @Inject
    transient private LegacyRepository legacyRepository;
    @Inject
    transient private LegacyJsfConverter legacyConverter;
    @Inject
    transient private LegacySearchForm legacySearchForm;

    private Legacy[] selectedRows;

    @Override
    protected Repository<Legacy, LegacyPk> getRepository() {
        return legacyRepository;
    }

    @Override
    protected Converter getConverter() {
        return legacyConverter;
    }

    @Override
    protected GenericSearchForm<Legacy, LegacySearchForm> getSearchForm() {
        return legacySearchForm;
    }

    @Override
    protected ConversationContext<Legacy> getSelectedContext(Legacy selected) {
        if (selected.isIdSet()) {
            // just the id matters as we want to reload it in the conversation entity manager.
            return LegacyController.newEditContext(selected.getId());
        } else {
            return LegacyController.newEditContext(selected); // fresh entity (creation)
        }
    }

    // -----------------------------------
    // Multi selection support
    // -----------------------------------

    public void setSelectedRows(Legacy[] selectedRows) {
        this.selectedRows = selectedRows;
    }

    public Legacy[] getSelectedRows() {
        return selectedRows;
    }

    public String multiSelect() {
        return getCurrentConversation() //
                .<ConversationContext<Legacy>> getCurrentContext() //
                .getCallBack() //
                .selected(Arrays.asList(selectedRows));
    }
}